"""Changed DB name

Revision ID: ecf9f7c837bf
Revises: de71b04c061a
Create Date: 2023-06-27 10:42:47.378751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf9f7c837bf'
down_revision = 'de71b04c061a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
