"""added google_api

Revision ID: bcb359bd07a7
Revises: ecf9f7c837bf
Create Date: 2023-06-30 20:39:16.745379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb359bd07a7'
down_revision = 'ecf9f7c837bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
